version: "3.8"

services:
    # local-mysql:
    #     platform: linux/amd64
    #     restart: always
    #     image: mysql:8
    #     command: --default-authentication-plugin=mysql_native_password
    #     ports:
    #         - 3306:3306
    #     environment:
    #         - MYSQL_ROOT_PASSWORD=root
    #     volumes:
    #         - mysql8-data:/var/lib/mysql
    #     networks:
    #         - local-mysql
    api:
        build: .
        command: npm run dev
        volumes:
            - ./src:/app/src
        ports:
            - 3000:3000
        expose:
            - "3000"
        networks:
            - local-mysql
volumes:
    mysql8-data:
networks:
    local-mysql:
        external: true
